# Generated by Django 5.1.4 on 2025-01-08 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, "Value can't be less than zero"), django.core.validators.MaxValueValidator(5, "Value can't be greater than five")]),
        ),
    ]
